# Fix mis-aligned LINKEDIT string pool with Apple's newer linkers
# This applies to proc-macros built as part of Android build
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-ld_classic"]

[build]
jobs = 4
